// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  // Generated by `shadcn-vue add`; keep it as the CLI wrote it so updates stay a clean diff.
  ignores: ['app/components/ui/**'],
})
